### ISSUE TITLE
Lepszy markdown

### ISSUE THREAD

**Issue by PerzotProgrammer** [Pawi1/t19#22]
Dzień dobry,
twoje repo to wielki syf.
Dodałbyś jakąś nawigacje do readme.md na mainie dla łatwiejszej nawigacji a nie miział dziewczyne :3
thx.

**Comment by Pawi1** [comment]
![image](https://github.com/Pawi1/t19/assets/114557817/eedc565e-61d1-4c12-8748-eab5decc4e54)
